
-- ======================================================
-- SEMS PRO v4.0 - DATABASE ARCHITECTURE
-- ======================================================

-- 1. STAGES TABLE
CREATE TABLE IF NOT EXISTS stages (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    total_students INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. STUDENTS TABLE (Compatible with Noor System)
CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    student_id TEXT,
    stage_id BIGINT REFERENCES stages(id) ON DELETE CASCADE,
    grade TEXT,
    class TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. COMMITTEES TABLE (Independent Stage Distribution Support)
CREATE TABLE IF NOT EXISTS committees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    location TEXT,
    capacity INTEGER DEFAULT 20,
    invigilator_count INTEGER DEFAULT 1,
    stage_counts JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. ACTUAL DISTRIBUTION LINKING
CREATE TABLE IF NOT EXISTS committee_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    committee_id UUID REFERENCES committees(id) ON DELETE CASCADE,
    student_id TEXT REFERENCES students(id) ON DELETE CASCADE,
    is_manual_override BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(student_id)
);

-- 5. CLEANUP FUNCTION
CREATE OR REPLACE FUNCTION reset_distribution_v4()
RETURNS void AS $$
BEGIN
    UPDATE committees SET stage_counts = '{}'::jsonb;
    DELETE FROM committee_students WHERE is_manual_override = FALSE;
END;
$$ LANGUAGE plpgsql;
