
-- ======================================================
-- SEMS PRO v4.0 - DATABASE ARCHITECTURE (Supabase)
-- نظام إدارة الاختبارات الذكي - هيكلة قاعدة البيانات
-- ======================================================

-- 1. STAGES TABLE
-- تخزين المراحل الدراسية (أول ثانوي، ثاني ثانوي، إلخ)
CREATE TABLE IF NOT EXISTS stages (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    total_students INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. STUDENTS TABLE
-- تخزين بيانات الطلاب المستوردة من نظام نور
CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY, -- المعرف الفريد للطلاب
    name TEXT NOT NULL,
    student_id TEXT, -- السجل المدني أو رقم الهوية
    stage_id BIGINT REFERENCES stages(id) ON DELETE CASCADE,
    grade TEXT,
    class TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. COMMITTEES TABLE
-- تخزين اللجان وقاعات الاختبارات مع التوزيع الآلي
CREATE TABLE IF NOT EXISTS committees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL, -- رقم اللجنة (مثلاً: 1، 2، 3)
    location TEXT, -- المقر (مثلاً: قاعة رقم 5)
    capacity INTEGER DEFAULT 30, -- السعة الافتراضية المعتمدة (30 طالباً)
    invigilator_count INTEGER DEFAULT 1, -- عدد الملاحظين المطلوبين للجنة
    stage_counts JSONB DEFAULT '{}'::jsonb, -- مصفوفة التوزيع (مثلاً: {"أول ثانوي": 15, "ثالث ثانوي": 15})
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. COMMITTEE_STUDENTS (DISTRIBUTION LINKING)
-- جدول الربط الفعلي بين الطلاب واللجان لضمان استمرارية البيانات
CREATE TABLE IF NOT EXISTS committee_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    committee_id UUID REFERENCES committees(id) ON DELETE CASCADE,
    student_id TEXT REFERENCES students(id) ON DELETE CASCADE,
    is_manual_override BOOLEAN DEFAULT FALSE, -- هل تم التعديل يدوياً؟
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(student_id) -- الطالب لا يمكن أن يكون في لجنتين في نفس الوقت
);

-- 5. NOTIFICATIONS TABLE
-- سجل العمليات والأحداث الحية في النظام
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'INFO', -- SUCCESS, ALERT, ERROR, INFO
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. RESET DISTRIBUTION FUNCTION
-- وظيفة SQL لتصفير التوزيع الحالي بالكامل بضغطة زر
CREATE OR REPLACE FUNCTION reset_distribution_v4()
RETURNS void AS $$
BEGIN
    -- تصفير عدادات المراحل داخل جدول اللجان
    UPDATE committees SET stage_counts = '{}'::jsonb;
    
    -- حذف جميع سجلات ربط الطلاب إلا إذا كانت مثبتة يدوياً
    DELETE FROM committee_students WHERE is_manual_override = FALSE;
END;
$$ LANGUAGE plpgsql;

-- 7. RLS POLICIES (إعدادات الأمان)
-- تفعيل حماية البيانات (اختياري حسب إعدادات Supabase)
ALTER TABLE stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE committees ENABLE ROW LEVEL SECURITY;
ALTER TABLE committee_students ENABLE ROW LEVEL SECURITY;

-- سياسات الوصول المفتوح لضمان عمل التطبيق السحابي مباشرة
CREATE POLICY "Access All Stages" ON stages FOR ALL USING (true);
CREATE POLICY "Access All Students" ON students FOR ALL USING (true);
CREATE POLICY "Access All Committees" ON committees FOR ALL USING (true);
CREATE POLICY "Access All Distribution" ON committee_students FOR ALL USING (true);
